/*
 * Created for the Lost Crafters SMP (https://www.lostcrafterssmp.com)
 * Licensed under the GNU Affero General Public License v3.0
 * See LICENSE.txt for full license information
 */

/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package ca.fireball1725.lcs.discordbot

import kotlin.test.Test
import kotlin.test.assertNotNull

class AppTest {
//    @Test fun appHasAGreeting() {
//        val classUnderTest = App()
//        assertNotNull(classUnderTest.greeting, "app should have a greeting")
//    }
}
